stages:
  data_ingestion:
    cmd: python .\src\data\data_ingestion.py
    deps:
    - .\src\data\data_ingestion.py
    params:
    - data_ingestion.random_state
    - data_ingestion.test_size
    outs:
    - .\data\raw\

  text_preprocessing:
    cmd: python .\src\features\text_preprocessing.py train.csv test.csv
    deps:
    - .\data\raw\
    - .\src\features\text_preprocessing.py
    outs:
    - .\data\processed\