data_ingestion:
  test_size: 0.2
  random_state: 42

feature_engineering:
  max_features: 5000

train:
  random_forest:
    max_depth: 6
    n_estimators: 200
    max_samples: 0.8
    n_jobs: -1
    random_state: 42
    oob_score: True
    verbose: 2